apiVersion: platform.confluent.io/v1beta1
kind: FlinkEnvironment
metadata:
  name: flink-env1
  namespace: flink
spec:
  kubernetesNamespace: flink
  flinkApplicationDefaults:
    spec:
      flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
  cmfRestClassRef:
    name: sudo
    namespace: flink
