apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: trust-bundle
  namespace: confluent
spec:
  sources:
  - useDefaultCAs: true
  # - secret:
  #     name: "root-secret"
  #     key: "ca.crt"

  # Another Secret source, but this time using a label selector instead of a named Secret
  - secret:
      selector:
        matchLabels:
          controller.cert-manager.io/fao: "true"
      key: "tls.crt"

  # - secret:
  #     name: "my-regional-cas"
  #     includeAllKeys: true

  target:
    configMap:
      key: "truststore.pem"
    additionalFormats:
      jks:
        key: "truststore.jks"
      pkcs12:
        key: "truststore.p12"
