apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-server:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  listeners:
    controller:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
  authorization:
    type: rbac
    superUsers:
      - User:kafka
  dependencies:
    mdsKafkaCluster:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
  replicas: 1
  configOverrides:
    server:
      - default.replication.factor=1
      - min.insync.replicas=1
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  authorization:
    type: rbac
    superUsers:
      - User:kafka
  replicas: 1 
  metricReporter:
    enabled: false
  configOverrides:
    server:
      - "default.replication.factor=1"
      - "min.insync.replicas=1"
      - "confluent.license.topic.replication.factor=1"
      - "confluent.tier.metadata.replication.factor=1"
      - "confluent.metadata.topic.replication.factor=1"
      - "confluent.balancer.topic.replication.factor=1"
      - "confluent.security.event.logger.exporter.kafka.topic.replicas=1"
      - "event.logger.exporter.kafka.topic.replicas=1"
      - "offsets.topic.replication.factor=1"
  image:
    application: confluentinc/cp-server:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 10Gi
  listeners:
    internal:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
    external:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
  services:
    mds:
      tokenKeyPair:
        secretRef: mds-token
      provider:
        file:
          secretRef: file-secret
  dependencies:
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: kafka-client
    kRaftController:
      controllerListener:
        authentication:
          type: plain
          jaasConfig:
            secretRef: credential
      clusterRef:
        name: kraftcontroller
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
