---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-bob-hack # Note: this was added to allow the environments endpoint to be accessed by CFK which is used as a health check upon startup
  namespace: confluent
spec:
  principal:
    type: user
    name: bob
  resourcePatterns:
    - name: '*'
      patternType: LITERAL
      resourceType: FlinkEnvironment
  role: DeveloperRead
  clustersScopeByIds:
    cmfId: CMF-id
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-bob
  namespace: confluent
spec:
  principal:
    type: user
    name: bob
  resourcePatterns:
    - name: flink-env1
      patternType: LITERAL
      resourceType: FlinkEnvironment
  role: DeveloperRead
  clustersScopeByIds:
    cmfId: CMF-id
