---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-alice-hack # Note: this was added to allow the environments endpoint to be accessed by CFK which is used as a health check upon startup
  namespace: confluent
spec:
  principal:
    type: user
    name: alice
  resourcePatterns:
    - name: '*'
      patternType: LITERAL
      resourceType: FlinkEnvironment
  role: DeveloperRead
  clustersScopeByIds:
    cmfId: CMF-id
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-alice
  namespace: confluent
spec:
  principal:
    type: user
    name: alice
  resourcePatterns:
    - name: flink-env1
      patternType: LITERAL
      resourceType: FlinkEnvironment
  role: DeveloperManage
  clustersScopeByIds:
    cmfId: CMF-id
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-alice-app
  namespace: confluent
spec:
  clustersScopeByIds:
    cmfId: CMF-id
    flinkEnvironmentId: flink-env1
  principal:
    name: alice
    type: user
  resourcePatterns:
  - name: '*'
    patternType: LITERAL
    resourceType: FlinkApplication
  role: DeveloperManage
  