---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-sudo-admin
  namespace: confluent
spec:
  principal:
    type: user
    name: sudo
  role: ClusterAdmin
  clustersScopeByIds:
    cmfId: CMF-id
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-alice
  namespace: confluent
spec:
  principal:
    type: user
    name: alice
  resourcePatterns:
    - name: flink-env1
      patternType: LITERAL
      resourceType: FlinkEnvironment
  role: DeveloperManage
  clustersScopeByIds:
    cmfId: CMF-id
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: cmf-rb-bob
  namespace: confluent
spec:
  principal:
    type: user
    name: bob
  resourcePatterns:
    - name: flink-env1
      patternType: LITERAL
      resourceType: FlinkEnvironment
  role: DeveloperRead
  clustersScopeByIds:
    cmfId: CMF-id
